supabase_config:
  supabase_url: "https://hsvnifjcvymrqnuacfsg.supabase.co"
  supabase_publishable_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhzdm5pZmpjdnltcnFudWFjZnNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNTkyMTEsImV4cCI6MjA2NDgzNTIxMX0.klK46_OGoTWyJHyJ4OeZZ_7_RmBMrSL1I1u41GZEfto"

database:
  # Additional database config if needed in future

distributor:
  name: "Triumph"
  full_name: "Triumph Nepal"
  logo_url: "https://www.triumphmotorcyclesnepal.com/wp-content/uploads/2024/12/triumph-white-logo.png"
  website: "https://www.triumphmotorcyclesnepal.com"

vehicle_types: ["bike"] # Options: ["car"], ["bike"], ["car", "bike"]

vehicle_models:
  bike:
    - model: "Speed"
      variants:
        - { name: "400", engine_capacity: 399, years: [2022, 2023, 2024, 2025] }
    - model: "Scrambler"
      variants:
        - { name: "400X", engine_capacity: 399, years: [2022, 2023, 2024, 2025] }
  car: []

selectable_colors:
  - { name: "Black", hex: "#000000" }
  - { name: "White", hex: "#FFFFFF" }
  - { name: "Silver", hex: "#C0C0C0" }
  - { name: "Red", hex: "#FF0000" }
  - { name: "Blue", hex: "#0000FF" }
  - { name: "Green", hex: "#008000" }
  - { name: "Yellow", hex: "#FFFF00" }

color_theme:
  primary: "#000000" # Triumph Black
  secondary: "#FFFFFF" # White
  tertiary: "#F6F6F6" # Light Gray
  accent: "#faf7f2" # Off-white
  muted: "#616670" # Dark Gray
  destructive: "#EF4444" # Red
  success: "#10B981" # Green
  warning: "#F59E0B" # Yellow

analytics_theme:
  # Chart colors for data visualization
  chart_colors: 
    - "#000000" # Primary (Triumph Black)
    - "#10B981" # Success (Green)
    - "#3B82F6" # Blue
    - "#8B5CF6" # Purple
    - "#F59E0B" # Warning (Yellow)
    - "#EF4444" # Destructive (Red)
    - "#06B6D4" # Cyan
    - "#EC4899" # Pink
  
  # Dashboard color scheme
  dashboard_background: "#FFFFFF" # White
  card_background: "#F9FAFB" # Light Gray
  grid_color: "#E5E7EB" # Gray
  text_color: "#1F2937" # Dark Gray
  axis_color: "#6B7280" # Gray

typography:
  primary_font: "Inter"
  secondary_font: "Inter"

currency:
  symbol: "Nrs"
  name: "Nepalese Rupees"

features:
  analytics: true
  customer_calls: true
  service_history: true
  coupon_system: true
  reports: true

business_settings:
  service_interval_km: 5000
  default_warranty_months: 24
  service_types:
    - "Regular Service"
    - "Major Service"
    - "Engine Overhaul"
    - "Brake Service"
    - "Oil Change"
    - "Chain & Sprocket"
    - "Tire Replacement"
    - "Battery Service"
    - "Pre-Delivery Inspection"