// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { config } from '@/config';

const SUPABASE_URL = config.supabase_config.supabase_url;
const SUPABASE_PUBLISHABLE_KEY = config.supabase_config.supabase_publishable_key;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);